### ISSUE TITLE
Allow soft deleted events and clients to be versioned afresh

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#134]
- [ ] Allow soft deleted events and clients to be versioned afresh.

- [ ] This will allow other clients to be able to detect deleted events and clients and also mark them as deleted locally

**Comment by githengi** [comment]
closing this issue as this can be achieved by syncing an archive event that can be used to delete the client if it exists
https://github.com/OpenSRP/opensrp-client-reveal/pull/639

**Comment by Rkareko** [comment]
@githengi @moshthepitt  @Wambere We need to implement this so that we can cater for objects that were deleted on the client then synced days later to the server. 
These will not be fetched using the current implementation of https://github.com/OpenSRP/opensrp-server-web/issues/188

**Comment by Wambere** [comment]
@Rkareko a couple of questions
- Is soft delete a new feature? I thought initially we would just delete and not soft delete?
- What does version afresh mean?

Then also to @githengi @moshthepitt what does this mean for all the other things like tasks which we say we don't delete but in actual sense do all the time? Can we only soft delete those too?

**Comment by Rkareko** [comment]
@Wambere soft delete is not a new feature. Events are not deleted from the database completely they are just archived (marked as deleted) i.e `date-deleted` field is populated.
Version afresh means to create a new server version after a soft delete.

**Comment by Wambere** [comment]
Okay, @Rkareko so from what I understand 
- we will now soft delete (archive) events and clients
- when we soft delete events and clients we will have a new event with a new serverVersion
- the above information/events will also be available from the getAll endpoint
- we will still delete (and not soft delete) tasks which are linked to archived/soft deleted events and clients
- we will never delete jurisdictions, structures, plans. Only archive / mark as inactive

Is all the above correct? If yes then I'm all for this plan

**Comment by Rkareko** [comment]
@Wambere  A few corrections

- When events and clients are soft deleted they are assigned a new server version
- Tasks are not deleted
