### ISSUE TITLE
 GetAll Identifiers filter by server version

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#149]
Limit the GetAll Identifiers methods to a reasonable limit  e.g 1000-5000.

Currently the getAll methods that returns all identifiers don't have any filter and perform a table scan to get all the current identifiers.

Add server version as a filter to only return identifiers that have been created after that particular server version.

Add an index on the server version so that the search, sort and limit happens on the index and not an using onMemory heapsort.

e.g for events

`create index event_metadata_server_version_idx on core.event_metadata(server_version);`

and then the query to be executed to be 

`select server_version, document_id from core.event_metadata where server_version > 0 order by 1 limit 1000`

The function should pick the last `server_version` and return to the API so that it can be used for the next invocation

**Comment by githengi** [comment]
@moshthepitt what is your thoughts on the above, this means you have to track the server version for the getAll enpoints

**Comment by moshthepitt** [comment]
@githengi we discussed with @wambere and we are good with the changes being discussed here.
