### ISSUE TITLE
Update tests for Location repository methods used to build location hierarchies

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-server-core#280]
Update tests for the following repository methods to ensure they preserve the order of the records fetched from the database

- [ ] `org.opensrp.repository.postgres.LocationRepositoryImpl#findLocationWithDescendants`
- [ ] `org.opensrp.repository.postgres.LocationRepositoryImpl#findParentLocationsInclusive`

**Comment by githengi** [comment]
Project: OpenSRP core

**Comment by rehammuzzamil** [comment]
As per my understanding, we need to add more assertions to ensure that the order is correct and also make sure the date is correct.
