### ISSUE TITLE
Generate Ids if its empty

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#301]
- [ ] Generate Ids if its empty 

- [ ] Currently there was a client that was posted having blank _id, this meant that an _id was not generated.

- [ ] Client, events with _id empty or null should always generate new _ids

**Comment by githengi** [comment]
Check on all repositories

**Comment by githengi** [comment]
Project: Opensrp Core

**Comment by rehammuzzamil** [comment]
Following Repositories requires are affected:

- ActionRepository
- AlertsRepository
- ClientsRepository
- ErrorTraceRepository
- EventsRepositoryImp
- MultimediaRepository
- ReportsRepository
- SettingsRepository
- StocksRepository
- ViewConfigurationRepository
cc : @githengi  @dubdabasoduba
