### ISSUE TITLE
Allow disabling of plan eveluation

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#317]
Currently `plan.evaluation.enabled` defined in opensrp.properties is used to control if evaluation is disabled.

This is enforced when saving or updating events.

However when plans are being updated/created this is enabled by default if the plan is dynamic. Since Thailand wants to disable to use OpenSRP task generation while using dynamic plans.

Using the `plan.evaluation.enabled` config will not be ideal since its used to control evaluation of plans events who control en events are modified/created.

- [ ] Since there is already a useContext that nifi uses to control if it should generate tasks or not, this would be ideal also for  OpenSRP to use useContext to flag that the plan is not valid for task generation

- [ ] `taskGenerationStatus` should be renamed to `externalTaskGenerationStatus` so that when its true then OpenSRP skips task generation and nifi generates the tasks.

**Comment by Wambere** [comment]
If we change the name that would mean updating all plans. Instead of changing let's just use `taskGenerationStatus` as is and set it to `internal` when we want openSRP to generate tasks. 
Normally plans are generated with it set to `false` so it should ignore all unless set specifically

**Comment by githengi** [comment]
@Wambere that is okay with me
