### ISSUE TITLE
Zambia Production team assignment doesn't seem to be removing assignment

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-server-core#325]
Unassignment doesn't appear to be happening on Zambia production. I suspect this is an issue with the OpenSRP server not removing assignments when they are updated from the web UI.

Here's what I see:
I did a team assignment at OA level in the web UI
The web UI POSTed the following
```
[
  {
    "fromDate": "2020-09-22T12:28:56-07:00",
    "jurisdiction": "cf8f72a5-2c2c-4860-923e-6403b03856f2",
    "organization": "d5857138-4172-529e-bb8d-411d73381c27",
    "plan": "7e4aba56-d5cc-5b3c-9e01-966e757c389e",
    "toDate": "2020-10-09T00:00:00-07:00"
  }
]
```
That all looks right. Today is the 22nd of Sept 2020.

I then undid that team assignment and here's what posted from the web UI
```
[
  {
    "fromDate": "2020-09-22T12:28:56-07:00",
    "jurisdiction": "cf8f72a5-2c2c-4860-923e-6403b03856f2",
    "organization": "d5857138-4172-529e-bb8d-411d73381c27",
    "plan": "7e4aba56-d5cc-5b3c-9e01-966e757c389e",
    "toDate": "2020-09-22T12:29:06-07:00"
  }
]
```

The to and from dates are now, which is what we needed to send. When I get it from the API, I get the following. This shows up also in the get by planIdentifier, but doesn't display them in the web UI.
```
[
    {
        "organizationId": "d5857138-4172-529e-bb8d-411d73381c27",
        "jurisdictionId": "cf8f72a5-2c2c-4860-923e-6403b03856f2",
        "planId": "7e4aba56-d5cc-5b3c-9e01-966e757c389e",
        "fromDate": 1600725600000,
        "toDate": 1600725600000
    }
]
```
The UNIX time translation for 1600725600 is 2020-09-21T22:00:00+00:00
Historically, these have disappeared because they were expired the day before. I'm not sure why they aren't disappearing now.

When I POST the following directly to the API they disappear.
```
[
    {
        "organization": "d5857138-4172-529e-bb8d-411d73381c27",
        "jurisdiction": "cf8f72a5-2c2c-4860-923e-6403b03856f2",
        "plan": "7e4aba56-d5cc-5b3c-9e01-966e757c389e",
        "fromDate": "2020-09-21T00:00:00.000Z",
        "toDate": "2020-09-21T00:00:00.000Z"
    }
]
```

Expected Behaviour
- Team assignments should disappear if they are unassigned.

**Comment by githengi** [comment]
@Rkareko this is the suggested implementation plan
Add an active column on `organization_location ` table. This will be used to track the active locations assignments

Remove `organization_location_organization_id_location_id_plan_id_key` constraint 

When doing an assignment check if there is an existing assignment,  return an error if there is an existing assignment and new assignment has different from data

Investigate use of Exclusion constraint to enforce integrity on the database

**Comment by githengi** [comment]
DDL changes done https://github.com/OpenSRP/opensrp-server-configs/pull/98

@Rkareko for getting the user assignment, lets not include the to_date so that assignments are valid upto the date but not inclusive.

Also update the mappers and make sure the duration is populated before saving
