### ISSUE TITLE
Import EUSM csv locations into locations API

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-core#351]
CSV is located [here](https://docs.google.com/spreadsheets/d/1bqIKxWbzkTv03fA1cIBOOJMgl8dQRxD2AymkjQ7Aljs/edit#gid=0).

Here is the structure of the CSV:

`country, region, district, commune, service_point_name, service_point_type, admin_level_tag, lat, long`

Latitude and longitude are optional. The rest of the fields are required.

**Comment by cafootitt** [comment]
@githengi can you flesh out this issue by COB on Monday, Nov 16? Benn will be picking this up first thing Tuesday.

**Comment by githengi** [comment]
To import the File transform the Input file to have a 1 row for each record e.g 

id | Name | parentId | status | version | geographicLevel | LocationTag name | LocationTag id
-- | -- | -- | -- | -- | -- | -- | --

Import the input into https://www.convertcsv.com/csv-to-json.htm

Use this template to convert into location json


```
  {lb}
     "{h1}":"{f1}" , "type" :"Feature"  ,
"properties": {
"{h2}":"{f2}"    ,"{h3}":"{f3}"    ,"{h4}":"{f4}"    ,"{h5}":{(f5)==""?"null":f5}    ,"{h6}":{(f6)==""?"null":f6}   
},
"locationTags":[ { "{name}":"{f7}"    ,"{id}":{(f8)==""?"null":f8}   }]
 {rb}
```

Format the JSON and then run the below commands to post the locations via the ApI.
```
split -l 640  structures-corrected.json part
for file in part* ; do  truncate -s-3 $file ; done
for file in part* ; do  sed -i '1s/^/[\n/' $file ; done
for file in part* ; do  echo "]" >>  $file ; done
for file in part* ; do curl  -X POST -H "Content-Type: application/json"  -H 'Authorization: Bearer <Access Token here> ' \
   -d @$file  https://mg-eusm-staging.smartregister.org/opensrp/rest/location/add?is_jurisdiction=true ; done
```

For structures change the param to `add?is_jurisdiction=false` above

**Comment by githengi** [comment]
I have imported the locations above, @bennsimon import the structures

**Comment by githengi** [comment]
For Structures

This if the import format 

id | Name | parentId | status | version | geographicLevel | type | AdminLevelTag | Latitude | Longitude
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

The JSON template is 
```
 {lb}
     "{h1}":"{f1}" , "type" :"Feature"  ,
"properties": {
     "{h2}":"{f2}",   
     "{h3}":"{f3}",    
     "{h4}":"{f4}",
    "{h5}":{(f5)==""?"null":f5} ,
    "{h6}":{(f6)==""?"null":f6} ,  
    "{h7}":"{f7}"    ,
    "{h8}": "{f8}"    
},
geometry": {
    "coordinates": [
      {f10}
      {f9}
    ],
    "type": "Point"
  },
 {rb}
```

**Comment by githengi** [comment]
@cafootitt @bennsimon  FYI
Managed to import all the structures and Locations. Structures with coordinates missing either latitude and longitude were imported without coordinates

This is the [sheet](https://docs.google.com/spreadsheets/d/1tm80ZZTt_eajba9QV8-3NMB3fAiOl9CDUDAQdSCBItQ/edit#gid=471010679) used for import

**Comment by cafootitt** [comment]
@githengi This is great, thanks so much Sam.

**Comment by cafootitt** [comment]
This is finished, closing.
