### ISSUE TITLE
Invoke Plan evaluation on all method that add/update events on event service

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#377]
- [x] Invoke Plan evaluation on all method that add/update events on event service

- [x] Currently only the add method if enabled

**Comment by rehammuzzamil** [comment]
I believe that an update event would find for an event that traverses the identifiers inside the event object and returns the unique one. But, the event object of flag_problem has no identifiers thus it returns `java.lang.IllegalArgumentException: No event found with the given list of identifiers. Consider adding new!`
I have used the URL for the update event as` /rest/event/{uniqueId}`.
@githengi Please share your thoughts on this?

**Comment by githengi** [comment]
use `/rest/event/sync` to post events no need to add a new API
