### ISSUE TITLE
Get all children and grand children of a location

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-server-core#66]
Related to https://github.com/OpenSRP/opensrp-server-web/issues/90

**Comment by cKellyDesign** [comment]
@Rkareko @githengi - Does this ticket include work to allow more than 1000 results from the `location` endpoint (as discussed [hapa](https://github.com/onaio/reveal-frontend/issues/400#issuecomment-523918748)?) Or does the number of results limit need its own ticket?

cc @moshthepitt

**Comment by githengi** [comment]
@cKellyDesign It was not part of this ticket but its easy to implement this on this ticket

**Comment by moshthepitt** [comment]
@githengi it would be really cool to have it implemented as part of this ticket

**Comment by githengi** [comment]
@moshthepitt @cKellyDesign We shall implement it as part of this ticket, however we shall validate the maximum limit what we define as the max limit?

**Comment by cKellyDesign** [comment]
@githengi for now let's say 5000 as the new max limit since there are ~4600 locations under Namibia, or we can do 10000 to be more future-proof?
