### ISSUE TITLE
Implement Organization Repository and Service

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#69]
- [x] Implement Organization Repository and Service as [specification](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1159921677/Team+Structure+and+User+Assignment)

- [ ] Implement Organization Location and Team assignment Repository and Service as documented on [specification](https://smartregister.atlassian.net/wiki/spaces/REV/pages/1159921677/Team+Structure+and+User+Assignment)

**Comment by Rkareko** [comment]
Closing PR, will be tracked on #82
